### ISSUE TITLE
úkol 2

### ISSUE THREAD

**Issue by luciez** [luciez/python-tasks#3]
Ahoj Anet, posílám další úkol. Bonus byl velká dřina 😅 a vypsání jen jedenkrát že region neexistuje taky nebylo úplně snadné a přímočaré pro mě, ale nějak to nakonec dopadlo a funguje to 😁
https://github.com/luciez/python-tasks/blob/main/ukol-2.py

**Comment by AnetaPopelova** [comment]
Libi se mi, ze se ti to povedlo spojit do jednoho i s bonusem. To vidim poprve, gratuluji 👍

**Comment by luciez** [comment]
Dikyyy, to už pak nějak šlo, když jsem tomu přišla na kloub 😆
