### ISSUE TITLE
ukol 3

### ISSUE THREAD

**Issue by luciez** [luciez/python-tasks#4]
Ahoj Anet, tak víkend byl plodný a nakonec se mi (snad asi) podařil i ukol 3 https://github.com/luciez/python-tasks/blob/main/ukol-3.py 
Funguje jen tak dobře jak jsem schopná ho otestovat 😃  takže možná něco najdeš.

**Comment by AnetaPopelova** [comment]
Kontrola funguje 👍

Mam k tomu jen drobnost. Zadani rika, ze pokud neni cislo platne, uz se nemas ptat na text zpravy. 

> Tvůj program nejprve ověří pomocí první funkce správnost telefonního čísla. Pokud není platné, vypíše chybu, v opačném případě se zeptá na text zprávy a pomocí druhé funkce určí její cenu, kterou vypíše uživateli.

Jo a...

1. replace neni treba odnikud importovat, [koukni](https://www.w3schools.com/python/ref_string_replace.asp). 
2. Mezi funkci a parametry obvykle nedelame mezeru, takze to bude vypadat spis` def phone_number_validator(phone_number):` a pak pri volani `phone_number_validator (phone_number)`. Stejne plati pro `input` a `print`. 
3. Pokud je podminek vic, je lepsi si je rozdelit do nekolika kruku nebo zkusit citelneji [naformatovat](https://stackoverflow.com/questions/181530/styling-multi-line-conditions-in-if-statements).

Ale ukol uzaviram jako splneny 👍

**Comment by luciez** [comment]
Takže bys to spis vyřešila tak, že dáš vystup te fce True/False dle platnosti cisla a potom za podmínku tu druhou funkci? Já jsem si říkala, že když tam mám ten exit, tak se vlastně na text zprávy neptam, když číslo platné není. A když jsem to testovala, tak se opravdu neptám, resp. v terminálu mi nevyskočil input na vložení textu.

1. Ten import "se mi tam objevil sám" když jsem ho použila, ale je vlastne pravda, že jsem jeste testovala co se stane když ho pouziju jako replace (...neco..) takže to asi bude tím 🤭
2. ok, diky s timto mam problemy 😄  hlavne to podle me pisu pokazdý jinak
3. aha jasný

**Comment by AnetaPopelova** [comment]
No... mne tam ten input skace. Fakt :-D 

Vidim pak chybu cisla i vypoctenou cenu. 

A ano, staci pridat podminku, treba: if vysledek kontroly cisla true, zeptej se na text, jinak vyhod chybu.

![Screenshot 2022-10-10 at 23 06 53](https://user-images.githubusercontent.com/47115025/194952341-f9f54560-c877-4f66-9fb7-1efdce225782.png)
