### ISSUE TITLE
Ukol 5 - dědičnost

### ISSUE THREAD

**Issue by luciez** [luciez/python-tasks#6]
Ahoj, tady je ukol 5 - vybrala jsem si dědičnost, možná ještě odevrzdam i list comprehension, minimalne aspon vyzkouším, zatím mi to moc nešlo 😬 
https://github.com/luciez/python-tasks/blob/main/ukol-5.py

**Comment by AnetaPopelova** [comment]
👍 Tesim se na pripadne list comprehension :-)
