### ISSUE TITLE
Ukol 5 List Comprehension

### ISSUE THREAD

**Issue by luciez** [luciez/python-tasks#7]
Ahoj, prosím koukla bys aspon na reseni posledního podbodu ukolu "# Suma ploch zemí Evropy". Nejsem si jista jestli to mám podle zadání, nějak jsem to pochopila tak, že mám v list comprehension udělat i tu sumu, ale to mi nijak nejde, takže to mam takto vedle :) Díky

https://github.com/luciez/python-tasks/blob/main/ukol-5-LC.py

**Comment by AnetaPopelova** [comment]
Staci to tou sumou obalit (zkombinovat tvoje dva kroky v jeden), takze:
`area_europe = sum([stat.get("area", 0) for stat in staty if stat["region"] == "Europe"])`

P.S.: Nabizim alternativni reseni pro trojku:
`staty_metropole = {stat["name"]: stat["capital"] for stat in staty}`
